// TemplateEntitySchemas.swift
// Supporting Types and Extensions for QA Buddy PU/NC Template System
// Note: Core Data managed object classes are auto-generated by Xcode from .xcdatamodeld

import Foundation

// MARK: - Supporting Types

// Note: CoordinateSystem protocol and implementations moved to CoordinateSystemManager.swift
// for better organization and dependency management


/// Write-up status enum
enum WriteupStatus: String, Codable {
    case draft
    case pending
    case reviewed
    case approved
    case completed
}

/// Default configurations for aviation QA
struct DefaultConfigurations {
    /// Aircraft zones for inspection
    static let aircraftZones = [
        // Decks
        "A Deck",           // Passenger deck (top)
        "B Deck",           // Cargo deck (bottom)

        // Wings & Control Surfaces
        "Left Wing",
        "Right Wing",
        "Empennage",        // Tail section

        // Landing Gear
        "Left MLG",         // Main Landing Gear
        "Right MLG",
        "Left Wheel Well",
        "Right Wheel Well",
        "NLG",              // Nose Landing Gear

        // Cargo & Sections
        "Forward Cargo",
        "Aft Cargo",
        "48 Section",       // Aft pressure bulkhead area

        // Systems Bays
        "FW EE Bay",        // Forward Electronic Equipment
        "Aft EE Bay",       // Aft Electronic Equipment
        "Left AC Bay",      // Air Conditioning
        "Right AC Bay",
        "Flight Deck",

        // Power Units
        "Left Engine",
        "Right Engine",
        "APU"               // Auxiliary Power Unit
    ]

    /// Activity types for inspections
    static let activityTypes = [
        "Pre-Flight",
        "Post-Flight",
        "General Maintenance",
        "AOG"               // Aircraft On Ground
    ]
}
