// TemplateEntitySchemas.swift
// Supporting Types and Extensions for QA Buddy PU/NC Template System
// Note: Core Data managed object classes are auto-generated by Xcode from .xcdatamodeld

import Foundation

// MARK: - Supporting Types

/// Coordinate system protocols and implementations
protocol CoordinateSystem: Sendable {
    var systemName: String { get }
    var xLabel: String { get } // "X" or "STA"
    var yLabel: String { get } // "Y" or "WL"
    var zLabel: String { get } // "Z" or "BL"
}

/// Coordinate labels protocol
protocol CoordinateLabels {
    var xLabel: String { get }
    var yLabel: String { get }
    var zLabel: String { get }
}

/// Velocity coordinate system (X:Y:Z)
struct VelocitySystem: CoordinateSystem {
    let systemName = "Velocity"
    let xLabel = "X"
    let yLabel = "Y"
    let zLabel = "Z"
}

struct VelocityCoordinateLabels: CoordinateLabels {
    let xLabel = "X"
    let yLabel = "Y"
    let zLabel = "Z"
}

/// CMES coordinate system (STA:WL:BL)
struct CMESSystem: CoordinateSystem {
    let systemName = "CMES"
    let xLabel = "STA"
    let yLabel = "WL"
    let zLabel = "BL"
}

struct CMESCoordinateLabels: CoordinateLabels {
    let xLabel = "STA"
    let yLabel = "WL"
    let zLabel = "BL"
}



/// Write-up status enum
enum WriteupStatus: String, Codable {
    case draft
    case pending
    case reviewed
    case approved
    case completed
}

/// Default configurations for aviation QA
struct DefaultConfigurations {
    /// Aircraft zones for inspection
    static let aircraftZones = [
        // Decks
        "A Deck",           // Passenger deck (top)
        "B Deck",           // Cargo deck (bottom)

        // Wings & Control Surfaces
        "Left Wing",
        "Right Wing",
        "Empennage",        // Tail section

        // Landing Gear
        "Left MLG",         // Main Landing Gear
        "Right MLG",
        "Left Wheel Well",
        "Right Wheel Well",
        "NLG",              // Nose Landing Gear

        // Cargo & Sections
        "Forward Cargo",
        "Aft Cargo",
        "48 Section",       // Aft pressure bulkhead area

        // Systems Bays
        "FW EE Bay",        // Forward Electronic Equipment
        "Aft EE Bay",       // Aft Electronic Equipment
        "Left AC Bay",      // Air Conditioning
        "Right AC Bay",
        "Flight Deck",

        // Power Units
        "Left Engine",
        "Right Engine",
        "APU"               // Auxiliary Power Unit
    ]

    /// Activity types for inspections
    static let activityTypes = [
        "Pre-Flight",
        "Post-Flight",
        "General Maintenance",
        "AOG"               // Aircraft On Ground
    ]
}
